import {Composition} from 'remotion';
import {TemplateComposition} from './compositions/TemplateComposition';
import {OcrPresentation} from './compositions/OcrPresentation';

export const RemotionRoot: React.FC = () => {
	return (
		<>
			<Composition
				id="TemplateComposition"
				component={TemplateComposition}
				durationInFrames={300}
				fps={30}
				width={1920}
				height={1080}
				defaultProps={{
					template: {},
					input: {},
				}}
			/>
			<Composition
				id="OcrPresentation"
				component={OcrPresentation}
				durationInFrames={600}
				fps={30}
				width={1920}
				height={1080}
				defaultProps={{
					content: {
						titleText: 'Sample Presentation',
						subtitleText: 'Generated by OCR pipeline',
						introCaption: 'Automatic text extraction',
						callToAction: 'Share what you learned!',
						outroCaption: 'Powered by Remotion',
						audioTrack: undefined,
						flowchartSvg: undefined,
						theme: {
							primaryColor: '#2563eb',
							secondaryColor: '#7c3aed',
							backgroundColor: '#0f172a',
							accentColor: '#38bdf8',
							fontFamily: 'Inter, Arial, sans-serif',
						},
						chapters: [
							{
								id: 'chapter-1',
								title: 'Introduction',
								summary: 'Summaries and bullets are automatically generated.',
								bullets: ['Takeaways appear with kinetic motion.', 'Tables and diagrams fade in context.'],
								startSeconds: 0,
								endSeconds: 20,
							},
						],
					},
				}}
			/>
		</>
	);
};

