import React from 'react';
import {Composition} from 'remotion';
import {TemplateComposition} from './compositions/TemplateComposition';
import {OcrPresentation} from './compositions/OcrPresentation';
type TemplateCompositionProps = Parameters<typeof TemplateComposition>[0];
type OcrPresentationProps = Parameters<typeof OcrPresentation>[0];

const TemplateCompositionWrapper: React.FC<Record<string, unknown>> = (props) => (
	<TemplateComposition {...(props as unknown as TemplateCompositionProps)} />
);

const OcrPresentationWrapper: React.FC<Record<string, unknown>> = (props) => (
	<OcrPresentation {...(props as unknown as OcrPresentationProps)} />
);

export const RemotionRoot: React.FC = () => {
	return (
		<>
			<Composition
				id="TemplateComposition"
				component={TemplateCompositionWrapper}
				durationInFrames={300}
				fps={30}
				width={1920}
				height={1080}
				defaultProps={{
					template: {},
					input: {},
				}}
			/>
			<Composition
				id="OcrPresentation"
				component={OcrPresentationWrapper}
				durationInFrames={600}
				fps={30}
				width={1920}
				height={1080}
				defaultProps={{
					content: {
						titleText: 'Sample Presentation',
						subtitleText: 'Generated by OCR pipeline',
						introCaption: 'Automatic text extraction',
						callToAction: 'Share what you learned!',
						outroCaption: 'Powered by Remotion',
						audioTrack: undefined,
						flowchartSvg: undefined,
						theme: {
							primaryColor: '#2563eb',
							secondaryColor: '#7c3aed',
							backgroundColor: '#0f172a',
							accentColor: '#38bdf8',
							fontFamily: 'Inter, Arial, sans-serif',
						},
						chapters: [
							{
								id: 'chapter-1',
								title: 'Introduction',
								summary: 'Summaries and bullets are automatically generated.',
								bullets: ['Takeaways appear with kinetic motion.', 'Tables and diagrams fade in context.'],
								startSeconds: 0,
								endSeconds: 20,
							},
						],
					},
				}}
			/>
		</>
	);
};

